version: "3.3"

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    container_name: mysql-${APP_NAME}
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASS}
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASS}
    command:
      [
        "--default_authentication_plugin=mysql_native_password",
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
      ]
    volumes:
      - ./wp-data:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    container_name: phpmyadmin-${APP_NAME}
    links:
      - db
    ports:
      - ${APP_IP}:${PHPMYADMIN_PORT}:80
    environment:
      - PMA_ARBITRARY=1

  wordpress:
    depends_on:
      - db
    links:
      - db
    image: wordpress:latest
    container_name: wordpress-${APP_NAME}
    ports:
      - ${APP_IP}:${APP_PORT}:80
    restart: always
    command: bash -c "cd wp-content/themes && git clone https://github.com/MatheusKindrazki/easy-wordpress-theme.git ${APP_NAME} && cd ${APP_NAME} && rm -rf .git mu-plugins LICENSE && mv theme/* ./ && rm -rf theme"
    environment:  
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${WP_USER}
      WORDPRESS_DB_PASSWORD: ${WP_PASS}
      WORDPRESS_DB_NAME: ${WP_DB}
    working_dir: /var/www/html/${APP_NAME}
    volumes:
      - ./config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
      - ./${APP_NAME}:/var/www/html/${APP_NAME}
volumes:
  db_data: {}
